services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: event_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./Backend/Backend
      dockerfile: Dockerfile
    container_name: event_backend
    restart: always
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
    - .env

  frontend:
    build:
      context: ./Frontend
    container_name: event_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata: